### ISSUE TITLE
how to change options in the timeout

### ISSUE THREAD

**Issue by mkmecry** [angular-slider/ng5-slider#10]
``` TypeScript
options: Options = {
  floor: 0,
  ceil: 0
}
setTimeout(()=>{
  this.options.ceil = 300; // i want to change it later
})
```
I did not understand even by looking at the document.

**Comment by piotrdz** [comment]
Apologies for not replying earlier. I was on holiday with limited internet access. I hope that you found a solution for your problem.

In this case, it's due to how Angular change detection works on objects. It won't pick up the change to the nested value, because it does a quick and dirty comparison of object identity. However, there is a workaround, which is to re-create the object:
```
setTimeout(() => {
  const newOptions = Object.assign({}, this.options);
  newOptions.ceil = 300;
  this.options = newOptions;
});
```

**Comment by mkmecry** [comment]
I got the result I wanted! Thank you!

Because I have little experience, I did not know even by looking at the source code, I thought that it was a specification, I was giving up.

I implemented it by another method, but this will work out.
Thank you for your reply!

I do not understand English but rely on Google translation but I hope that it is transmitted.

**Comment by piotrdz** [comment]
No worries, I'm glad you found your own workaround. Google translate is awesome, isn't it? I can understand you without any problems.

**Comment by AdrienHorgnies** [comment]
I had a similar problem and tried a similar solution without success. My floor and ceil values come from http calls from onInit, I replace the options object from the subscription code but it doesn't seem to work.
```typescript
this.spaceService.minPrice().subscribe(value => {
    // the following line should update ng5-slider but doesn't.
    this.options = Object.assign({floor: value});
});
```

**Comment by piotrdz** [comment]
@AdrienHorgnies: `Object.assign` creates a new object based on the parameters you pass in. If you want to clone and modify an existing options object in one statement, you should do it like so:
```ts
this.options = Object.assign(this.options, {floor: value});
```

I created [this StackBlitz example](https://stackblitz.com/edit/ng5-slider-options-from-http-service?file=src%2Fapp%2Fapp.component.ts) to replicate this exact scenario when using HTTP API calls. I hope this helps.

**Comment by AdrienHorgnies** [comment]
@piotrdz I made a mistake indeed, I must have been sleepy. But be careful that Object.assign doesn't create a new object. It takes the first argument object and assigns it every fields from every object it receives afterwards. But if you put a new object as first argument, such as `{}`, it will indeed be a new object.
Your code is correct on StackBlitz but it is not in your comment as you're using `this.options` as first argument.

I've discussed this issue with a colleague of mine and he advised me to use an Observable and directly use this Observable in the html code with the pipe async. That way Angular will catch the event and update the slider.
I'll try that in the following days and post my solution here.

**Comment by piotrdz** [comment]
Yes, sorry, I copy-pasted the wrong code in my answer.

Your colleague is right, if you make multiple modifications to the options object, coming from different sources, it's best to use an observable.

**Comment by piotrdz** [comment]
Since people keep coming back to this issue, I added mention of this behaviour in API documentation and added another [demo example](https://angular-slider.github.io/ng5-slider/demos#dynamic-options-slider) to illustrate it.

**Comment by AdrienHorgnies** [comment]
Here is the setup I used if it can be of any used:
```html
        <ng5-slider (userChange)="onFilterFormChanges()" [(highValue)]="filters.priceMax.value"
                    [(value)]="filters.priceMin.value" [options]="{
        floor: minPrice | async,
        ceil: maxPrice | async,
        step: 10,
        translate: sliderText
    }"></ng5-slider>
```

```typescript
    ngOnInit() {
        this.minPrice = this.spaceService.minPrice().pipe(
            tap(value => this.filters.priceMin.value = value),
            startWith(20)
        );
        this.maxPrice = this.spaceService.maxPrice().pipe(
            tap(value => this.filters.priceMax.value = value),
            startWith(2900)
        );
    }
```
I couldn't get rid of a null pointer exception without the startWith and I need the tap as I use double binding with another member of the class.
