### ISSUE TITLE
How to pass ceil value as Attribute

### ISSUE THREAD

**Issue by ExploreGopal** [angular-slider/ng5-slider#100]
how to pass the ceil value as attribute to ng5-slider dynamically.

<ng5-slider [ceil]="each.ceil" [options]="options" ></ng5-slider>

**Comment by piotrdz** [comment]
`ceil` is part of options object so you need to modify it manually. There is an existing [example](https://angular-slider.github.io/ng5-slider/demos#dynamic-options-slider) which should help.

**Comment by ExploreGopal** [comment]
suppose slider in loop each object has independent ceil value.

**Comment by piotrdz** [comment]
You can always create separate options object for each slider. Does [this example](https://stackblitz.com/edit/ng5-slider-range-slider-dynamic-ceil-example?file=src/app/app.component.ts) help?

**Comment by ExploreGopal** [comment]
Thanks Piotr

**Comment by piotrdz** [comment]
I understand that this solution is acceptable, so I'm closing the ticket.

**Comment by fzs1994** [comment]
@piotrdz this is breaking in latest version(1.2.4) Working fine in old version(1.2.0)
[Stackblitz](https://stackblitz.com/edit/ng5-slider-range-slider-dynamic-ceil-example-o2lvdn)
