### ISSUE TITLE
Suggestion for demo scenarios

### ISSUE THREAD

**Issue by nickraphael** [angular-slider/ng5-slider#101]
You've got an amazing set of demos on your site.  I have a suggestion for another one.  Ok, let me explain...

Slider with range -100 to +100.  I want two arrows to drag.  But here's the thing - they are locked to each other so setting one to +50 will set the other to -50.  So the negative side of the scale mirrors the right side.  So as I drag the pointer, the other pointer moves automatically.

I assume that's possible...?

**Comment by nickraphael** [comment]
I've tried to update one value when the other one changed but I'm having issues.

```
<ng5-slider
        [value]="targetRangeLow"
        [highValue]="targetRangeHigh"
        [options]="sliderOptions"
        (valueChange)="sliderValueChange($event)"
        (highValueChange)="sliderHighValueChange($event)"
      ></ng5-slider>

  sliderValueChange(value: number) {
    this.targetRangeLow = value;
    this.targetRangeHigh = -value;
  }

  sliderHighValueChange(value: number) {
    this.targetRangeHigh = value;
    this.targetRangeLow = -value;
  }
```

It seems that setting the value of one from the even of the other causes issues.  It causes both events to fire.

**Comment by nickraphael** [comment]
I've tried everything.  It appears that even when the highValue is being set, the low value is also set.  So there is no way to know which one is being set.

**Comment by piotrdz** [comment]
You can achieve this using user change events. [This Stackblitz](https://stackblitz.com/edit/ng5-slider-issue-101?file=src%2Fapp%2Fapp.component.ts) should help.

**Comment by nickraphael** [comment]
@piotrdz  That works perfectly.  Love it.
