### ISSUE TITLE
Tick values are displayed even if showTicksValues option is set to false

### ISSUE THREAD

**Issue by rathodsanjay** [angular-slider/ng5-slider#105]
Even if the `showTicksValues` option is set to `false`, the tick values are displayed and it distorts the UI. Please refer to the attached screen shot:

![issue](https://user-images.githubusercontent.com/17136385/59099476-d078ca00-8940-11e9-8db2-56c8cdd2bfd1.png)

I am using the latest release **v1.2.0**
In my application, I have provided options to dynamically enable/disable the tick values. It works fine initially when the `showTicksValues` is `false`. But once, the `showTicksValues` is set to `true` and then changed back to `false`, this issue occurs.

Note that it was working fine with older version (v1.1.13, not sure since when it broke).

**Possible root cause & fix:**

In [slider.component.ts](https://github.com/angular-slider/ng5-slider/blob/master/src/ng5-slider/lib/slider.component.ts) in `updateTicksScale()`method, on **line #1246**, you have used `Object.assign(this.ticks[i], newTicks[i])` to replace existing tick with the new tick at the given index.

I guess doing so, **doesn't remove** the `value` of the tick from the old object even if the value is not present in the new tick. Thus, the tick tooltips still appear.

I guess that line should be changed to `this.ticks[i] = newTicks[i]` instead of using `object.assign()`.

**Comment by piotrdz** [comment]
Thanks for reporting this. I fixed the issue with another change as discussed in the pull request.

This is now available in master and I will include it in next release.

**Comment by piotrdz** [comment]
Fix now released in v1.2.1.
