### ISSUE TITLE
1.2.1 Sliders now seem to have animation on by default

### ISSUE THREAD

**Issue by tcoz** [angular-slider/ng5-slider#109]
After updating to 1.2.1, the sliders seem to "ease" by default. Animations is not set in the slider options. Does this now need to be turned off explicitly?

**Comment by piotrdz** [comment]
Yes, animations are turned on by default. If you want to turn them off, set `animate: false` in the options.

**Comment by tcoz** [comment]
I integrated and tested, looks good.
