### ISSUE TITLE
Regression: high value handle/pointer only snaps when setting a new maximum

### ISSUE THREAD

**Issue by willhs** [angular-slider/ng5-slider#110]
When I interact with the slider bar nearer to the high value than the low value I'd expect the high value handle to change, but if the point I interact with is lower than the high value, then the low value handle snaps to that point rather than the low value handle like I'd expect.

I noticed this regression from v1.1.12 to v1.2.1

**Comment by piotrdz** [comment]
Ah, I see. Another thing that I should be tested. I will fix it.

**Comment by piotrdz** [comment]
I pushed a fix to master and it will be available in next release.

**Comment by piotrdz** [comment]
Fix released in v1.2.2.
