### ISSUE TITLE
How to set the pointer size?

### ISSUE THREAD

**Issue by Lanseer** [angular-slider/ng5-slider#112]
I want to make a smaller pointer, but there is no way to support to make it

**Comment by piotrdz** [comment]
You have to override the default CSS style to change element sizes. [This Stackblitz](https://stackblitz.com/edit/ng5-slider-styled-slider-example?file=src%2Fapp%2Fapp.component.scss) does something similar by introducing custom CSS.

To change only a single dimension, you can start by copy-pasting the original SCSS from slider component and experiment with different settings. [This Stackblitz](https://stackblitz.com/edit/ng5-slider-variable-style-example?file=src/app/app.component.scss) should help.

Also check out [STYLING.md](https://github.com/angular-slider/ng5-slider/blob/master/STYLING.md) for overview of slider elements.

**Comment by Lanseer** [comment]
> You have to override the default CSS style to change element sizes. [This Stackblitz](https://stackblitz.com/edit/ng5-slider-styled-slider-example?file=src%2Fapp%2Fapp.component.scss) does something similar by introducing custom CSS.
> 
> To change only a single dimension, you can start by copy-pasting the original SCSS from slider component and experiment with different settings. [This Stackblitz](https://stackblitz.com/edit/ng5-slider-variable-style-example?file=src/app/app.component.scss) should help.
> 
> Also check out [STYLING.md](https://github.com/angular-slider/ng5-slider/blob/master/STYLING.md) for overview of slider elements.

**Comment by Lanseer** [comment]
yes, I found the way to make it ,and  thanks very much anyway!

**Comment by shahzaibexe** [comment]
i am working with ng5-slider. and I am facing the problem of adjusting the tick customize the height of different values  . plz help
