### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [angular-slider/ng5-slider#113]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/angular-slider/ng5-slider/blob/master/package.json#L71

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

Same applies to `path`, see https://github.com/angular-slider/ng5-slider/blob/master/package.json#L81

**Comment by piotrdz** [comment]
Thanks, you are right, I don't know how that ended up in package.json. Fortunately, these are only dev dependencies, which don't make it to the published NPM package.json.

I fixed it now in master.
