### ISSUE TITLE
max point not in correct position in mat-dialog

### ISSUE THREAD

**Issue by csadrianl** [angular-slider/ng5-slider#116]
Hi,

I'm trying to use the ng5 slider to a dynamic form and I noticed that upon setting the value and highValue have same values with floor and ceil, the max pointer position wasn't set on the same point of ceil. Here's a screenshot:
![image](https://user-images.githubusercontent.com/48675696/60346476-cc931180-99ed-11e9-9654-d9ca6a1c8159.png)

**Comment by csadrianl** [comment]
Hi,

Looks like this is same scenario as I encountered:
https://stackblitz.com/edit/ng5-slider-simple-slider-example-xgisko?file=src%2Fapp%2Fapp.component.html

**Comment by csadrianl** [comment]
Hi,

I tried that sample updating to 1.2.4 since its version before was 1.2.0

It looks like this wasn't same with my current scenario. My scenario is that I'm using ng5-slider on a dynamic form. I checked the CSS and it seems that there's an issue on max-pointer's "left" css I'm not sure how's this being computed to get the left value. Then I noticed that when slider became active the max-pointer will move to the right position:

before making the slider active:
![image](https://user-images.githubusercontent.com/48675696/60450137-c7d39500-9c5b-11e9-8f42-dba74addea82.png)

after the slider became active:
![image](https://user-images.githubusercontent.com/48675696/60450180-dc179200-9c5b-11e9-9f21-42858067e474.png)
*NOTE: the active indicator is on lower right side the blue dot one.

**Comment by csadrianl** [comment]
Hi,

I was able to replicate the issue. Btw, I'm using the ng5 slider on mat-dialog and this is where i encouter the issue:
https://ryvoxlloakx.angular.stackblitz.io/

**Comment by AskmeKolaric** [comment]
Hello, 
Any news how to fix this problem?

**Comment by MatteoFe** [comment]
> Hi,
> 
> Looks like this is same scenario as I encountered:
> https://stackblitz.com/edit/ng5-slider-simple-slider-example-xgisko?file=src%2Fapp%2Fapp.component.html

Hi, same problem here, but I found a workaround using 
`[style.display]="show ? 'block' : 'none'"`

here I modified your example:
https://ng5-slider-simple-slider-example-gmz2yy.stackblitz.io

**Comment by csadrianl** [comment]
Hi,

We were able to create a workaround using manualRefresh. We added the refresh on the constructor like this:

 constructor(public dialogRef: MatDialogRef<FilterComponent>) {
    this.dialogRef.afterOpen().subscribe(() => this.slidersRefresh.emit());

  }

After opening the dialog it was able to manually refresh the slider after opening the dialog

**Comment by AskmeKolaric** [comment]
@csadrianl 
How would you this in primeNG?
