### ISSUE TITLE
Small bug on documentation

### ISSUE THREAD

**Issue by ValentinH** [angular-slider/ng5-slider#12]
Hey @piotrdz, thanks again for the great work, you rock here!

I've just noticed a few bug on the "Custom scale" demo:
![image](https://user-images.githubusercontent.com/2678610/43677385-56edd30a-9801-11e8-9be7-e398e3140928.png)

It seems that there are 2 demos with the same name but the code example are not matching the examples.

**Comment by piotrdz** [comment]
Thanks @ValentinH for spotting this. I messed it up when I was splitting out the code to individual examples. It's fixed now.
