### ISSUE TITLE
Not working on Angular 8

### ISSUE THREAD

**Issue by lorenzonet** [angular-slider/ng5-slider#130]
After adding the package to my Angular 8 application I got these errors:

`npm WARN ng5-slider@1.2.4 requires a peer of @angular/core@>=5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN ng5-slider@1.2.4 requires a peer of @angular/common@>=5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN ng5-slider@1.2.4 requires a peer of @angular/forms@>=5.0.2 but none is installed. You must install peer dependencies yourself.
n`

and during compilation:

`ERROR in ../node_modules/ng5-slider/esm2015/ng5-slider.js
Module not found: Error: Can't resolve '@angular/common' in 'C:\...\node_modules\ng5-slider\esm2015'
ERROR in ../node_modules/@angular/forms/fesm2015/forms.js
Module not found: Error: Can't resolve '@angular/platform-browser' in 'C:\...\node_modules\@angular\forms\fesm2015'`

Do you mind telling me if the package is working on Angular 8+?

**Comment by vortaxg** [comment]
works fine on 
"@angular/animations": "^8.1.3",
    "@angular/cdk": "~8.1.1",
    "@angular/common": "^8.1.3",
    "@angular/core": "^8.1.3",
    "@angular/forms": "^8.1.3",

**Comment by lorenzonet** [comment]
Well, I managed to compile tha app after adjusting the packages as follow, the angular/common package was quite wacky...

![packages](https://user-images.githubusercontent.com/16530670/62144837-bd57fa00-b2f2-11e9-9878-f090907a8db2.jpg)

But I still get an error on runtime:
![slider_error](https://user-images.githubusercontent.com/16530670/62145210-4b33e500-b2f3-11e9-8766-587fa13a641a.png)

the second error is referring to this line
`<ng5-slider [(value)]="value" [(highValue)]="highValue" [options]="options"></ng5-slider>`

**Comment by cedx** [comment]
I confirm that it works fine with:

```json
{
    "@angular/animations": "^8.2.2",
    "@angular/common": "^8.2.2",
    "@angular/compiler": "^8.2.2",
    "@angular/core": "^8.2.2",
    "@angular/forms": "^8.2.2",
    "@angular/platform-browser": "^8.2.2"
}
```

**Comment by piotrdz** [comment]
Slider is working as expected, so closing this ticket.
