### ISSUE TITLE
ViewDestroyedError: Attempt to use a destroyed view: detectChanges

### ISSUE THREAD

**Issue by danielheth** [angular-slider/ng5-slider#140]
Running into a problem where I have Angular 8 and Angular Material... the slider is sitting in a mat-dialog and when it is closed, the detectChanges that runs every 250ms is firing and throwing thousands of errors in the chrome console that look like this: 

```Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges```

`detectChanges` appears in 3 locations... 

- https://github.com/angular-slider/ng5-slider/blob/9c0ceb140db6647465adade56fb134e5f27eaecb/src/ng5-slider/lib/slider.component.ts#L1064

- https://github.com/angular-slider/ng5-slider/blob/8c240a7ef67fca2b0f0d0ac3361d4614205320b9/src/ng5-slider/lib/slider.component.spec.ts#L34

- https://github.com/angular-slider/ng5-slider/blob/9c0ceb140db6647465adade56fb134e5f27eaecb/src/ng5-slider/lib/slider.component.ts#L372

**Suggested change is to check if destroyed prior to detectChanges();**
see: https://stackoverflow.com/a/46605947

**Comment by nekator** [comment]
We have several tests failing with the same error after upgrading to Angular 8.

**Comment by nekator** [comment]
I was able to fix the test. I had t call detectChanges manually after each change on the slider and I move the whole initialization into an async beforeEach block.

Now the errors are gone and the tests are runnig as expected.

**Comment by ThomasDevens** [comment]
Also still having this issue, above fix seems easy enough

**Comment by piotrdz** [comment]
Released in v1.2.5. Closing.
