### ISSUE TITLE
Angular 9 and Ivy

### ISSUE THREAD

**Issue by merobal** [angular-slider/ng5-slider#159]
With Ivy I got this warning:

`
WARNING in Entry point 'ng5-slider' contains deep imports into '/home/[repo]/node_modules/ng5-slider/node_modules/rxjs/Subject', '/home/[repo]/node_modules/ng5-slider/node_modules/rxjs/Subscription', '/home/[repo]/node_modules/ng5-slider/node_modules/rxjs/operators'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
`

Which is related to https://github.com/angular-slider/ng5-slider/issues/156

**Comment by ThomasDevens** [comment]
After upgrading from 8.2.3 to 9 i've also started to see this pop up, only happens when running angular's recommenced postinstall script `ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points`

**Comment by Daniyar111** [comment]
@merobal I also have this warning in angular 9, but range slider works perfectly.. Can I ignore it?.. Or can happens something wrong?

**Comment by Bnaffeti** [comment]
I have the same warning, after apgrading to Angular 9

**Comment by merobal** [comment]
I just found this now via Google search: https://github.com/m0t0r/ngx-slider

**Comment by talamaska** [comment]
actually it's pretty easy to override which rxjs to use. You just have to set the correct path in paths in tsconfig. Saw that somewhere in the other issues,

**Comment by rohyadav** [comment]
Is there any solution on this. i am also facing same issue while build a project.

**Comment by Doc999tor** [comment]
Updates?

**Comment by piotrdz** [comment]
This should be fixed by PR #216, which I just merged and will release as soon as possible.

Alternatively, v2.0 targeting Angular 6+ and rxjs 6+ is in the works, and will be available soon as well.

**Comment by piotrdz** [comment]
This has just gone out in v.1.2.5, and I have tested the slider successfully with all Angular versions 5 through 10, so I will close this ticket.

Further work with removing rxjs 5 dependency is coming in v2.0 in the next two days.

**Comment by talamaska** [comment]
What about 
npm WARN @angular-slider/ngx-slider@2.0.1 requires a peer of @angular/core@^6.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular-slider/ngx-slider@2.0.1 requires a peer of @angular/common@^6.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular-slider/ngx-slider@2.0.1 requires a peer of @angular/forms@^6.1.0 but none is installed. You must install peer dependencies yourself.

**Comment by piotrdz** [comment]
@talamaska My bad, see issue #219
