### ISSUE TITLE
has no exported member 'ChangeContext'

### ISSUE THREAD

**Issue by lgh06** [angular-slider/ng5-slider#17]
the demo https://angular-slider.github.io/ng5-slider/#user-events-slider  shows  
userChange event.

but cannot import 'ChangeContext'.
```
ERROR in src/app/booking-lot/booking-modals.component.ts(6,30): error TS2305: Module '"E:/dev/xcar/backend/node_modules/ng5-slider/ng5-slider"' has no exported member 'ChangeContext'.
```

**Comment by lgh06** [comment]
and when I do not import the ChangeContext, userChange event did nothing.

**Comment by piotrdz** [comment]
@lgh06 I haven't received any update or any other reports of this issue, so unless I have more information, I'm inclined to close this ticket.
