### ISSUE TITLE
BUG when build an angular 9 app

### ISSUE THREAD

**Issue by talamaska** [angular-slider/ng5-slider#181]
Warning: Entry point 'ng5-slider' contains deep imports into
 '-----/node_modules/ng5-slider/node_modules/rxjs/Subject',
 '-----/node_modules/ng5-slider/node_modules/rxjs/Subscription',
 -----/node_modules/ng5-slider/node_modules/rxjs/operators'. 
This is probably not a problem, but may cause the compilation of entry points to be out of order.

**Comment by xavierclotet** [comment]
Yes, can u upgrade to angular9,  please.

**Comment by DheerajVaranasi** [comment]
Can you please update to angular 9?

**Comment by gyanex** [comment]
i am also getting the same warning while building an angular 9 app.

**Comment by Sebi11** [comment]
Related to https://github.com/angular-slider/ng5-slider/issues/159

**Comment by rohyadav** [comment]
Is there any solution on this. i am also facing same issue while build a project.

**Comment by Sebi11** [comment]
The only solution is to make a PR to fix the imports (very easy) and hope for a release...

**Comment by merobal** [comment]
https://github.com/m0t0r/ngx-slider

**Comment by piotrdz** [comment]
This has been merged with PR #216, will release as soon as possible.

**Comment by piotrdz** [comment]
Released in v1.2.5. Closing.
