### ISSUE TITLE
custom styles not being applied

### ISSUE THREAD

**Issue by jfoxworth** [angular-slider/ng5-slider#185]
I am attempting to apply the custom styles for a "custom-slider" class as done in the example. Even when I turn off view encapsulation, the styles are not applied.

Any idea as to why this could be?

**Comment by jfoxworth** [comment]
Ahhh. I figured this out. I was putting the "custom-slider" class on the slider itself and not on the parent div.

**Comment by kj9933** [comment]
Use :ng-deep. It will work
::ng-deep {
    .slider_main_container .ng5-slider {
        height: 9px;
        margin: 50px 0 20px;
        .ng5-slider-bubble {
            background: #000000;
            color: white;
            margin-bottom: 40px;
            border-radius: 7px;
            padding: 20px 25px 20px 25px;
            display: flex;
            justify-content: center;
            align-items: center;
            align-content: center;
            bottom: 0;
            height: 36px;
            font-family: Avenir Medium;
            font-size: 20px;
        }
        .ng5-slider-tick-value{
            top: 25px;
        }
        .ng5-slider-bubble::after{
            content: " ";
            background: black;
            height: 25px;
            width: 25px;
            position: absolute;
            bottom: -11px;
            clip-path: polygon(100% 46%, 0 46%, 48% 100%);
        }
        .ng5-slider-limit{
            display: none;
        }
        .ng5-slider-bar{
            height: 10px;
            background-color: #DEDEDE;
            border-radius: 7px;
        }
        .ng5-slider-pointer:focus{
            border: none;
            outline: none;
        }
        .ng5-slider-pointer {
            cursor: pointer;
            width: 34px;
            height: 34px;
            top: -12px;
            background-color: #2446F6;
            z-index: 3;
            border-radius: 50px;
        }
        .ng5-slider-pointer:after {
            content: '';
            width: 26px;
            height: 26px;
            position: absolute;
            top: 4px;
            left: 4px;
            border-radius: 50px;
            background: #fff;
        }
    }
  }

**Comment by shafqatjan** [comment]
when we move first from left after redirect and response from API, selected bar get disturbed went outside of the rang, when we just click it gets fine

**Comment by piotrdz** [comment]
The main issue has been answered, so I will close the ticket.

@shafqatjan If you are still experiencing problems, please open a new ticket.
