### ISSUE TITLE
Angular 10 gives optimization bailout issue due to CommonJS/AMD module

### ISSUE THREAD

**Issue by Shofol** [angular-slider/ng5-slider#197]
C:\Users\shofol\Desktop\e-kyc\node_modules\ng5-slider\__ivy_ngcc__\esm2015\ng5-slider.js depends on 'rxjs/operators'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

I think we need a ES6 module for ng5-slider to get optimized results. Is there a module?

**Comment by piotrdz** [comment]
This has been merged with PR #216, will release as soon as possible.

**Comment by piotrdz** [comment]
Released in v1.2.5. Closing.
