### ISSUE TITLE
Only allow slider to move by sliding the button only

### ISSUE THREAD

**Issue by justsolarry** [angular-slider/ng5-slider#21]
Hi there, 

Is there a way to only allow the user to slide the slider by only using the **button** and not via clicking on the **slider** itself. 

Thanks

**Comment by piotrdz** [comment]
There is the option flag `onlyBindHandles`, see this [StackBlitz example](https://stackblitz.com/edit/angular-unrqag?file=src%2Fapp%2Fapp.component.ts). Does that work for your use case?

**Comment by justsolarry** [comment]
Awesome, that works great. I must have missed it while reading the API docs. Thanks!
