### ISSUE TITLE
ngOnDestroy throwing an exception

### ISSUE THREAD

**Issue by silvl** [angular-slider/ng5-slider#215]
Sometimes ngOnDestroy may be called before ngOnInit.  [Refer to article](https://www.bennadel.com/blog/3356-ngoninit-may-not-get-called-before-ngondestroy-is-called-in-angular-4-4-6.htm)

When this happens, SliderComponent.ngOnDestroy is throwing an exception and causing issues when trying to embed this control in ngx-formly.

Please add try/catch in ngOnDestroy or check if have elements, etc. The error is thrown in unbindEvents(), element is undefined and calling element.off() results in an exception.

**Comment by piotrdz** [comment]
This has been merged with PR #216, will release as soon as possible.

**Comment by piotrdz** [comment]
Released in v1.2.5. Closing.
