### ISSUE TITLE
Accessibility: e.g. changing value from 1000 to 500

### ISSUE THREAD

**Issue by rkristelijn** [angular-slider/ng5-slider#218]
When using only the keyboard, you are able to focus the values of both the upper- and lower bound and use arrow keys to change them.

This is great already!

However... when you have lower bounds 0 and upperbounds 1000, and you want to one of the values to 500, you need to press the arrow button 500 times.

It would be great to increase the size of the change step by 10% when using CTRL or Command and arrow keys, or an ability to toggle two inputs for the value and highValue

**Comment by piotrdz** [comment]
This is already available. Page Up and Page Down keys move the slider at 10% increments.

**Comment by rkristelijn** [comment]
@piotrdz Awesome! this is just what I needed. I would be great to have this documented such as on https://ng-bootstrap.github.io/#/components/datepicker/overview#keyboard-shortcuts

Can I make a PR to update README.md? Or do you rather have this documented on the 'official website'?

**Comment by piotrdz** [comment]
I added the documentation to README.md for now. I will pull some parts of README.md into the website as well, but that will be a bigger task for later.

This is now released in v1.2.6, so I will close the ticket.
