### ISSUE TITLE
ng5-slider accomodate range of -something to +something with proper stepping

### ISSUE THREAD

**Issue by jigsshah** [angular-slider/ng5-slider#23]
Hi,

I am ng5-slider to accommodate a range of -something to +something, however, this something value is what I a get from the HTTP service call. So based on the example I used  [(value)]="minValueVariable" and [(highValue)]="maxValueVariable" but for the step what value should i provide current the step value is 5.0 .So the negative value is directly moved to 0 and then the positive one works fine with the stepping.
Can you please look into this one and provide an update on the same.

Warm regards,
Jigar

**Comment by piotrdz** [comment]
It sounds like you want to change the options object on receiving the new limit value.

Does [this example](https://stackblitz.com/edit/angular-ixpp2k?file=src%2Fapp%2Fapp.component.ts) help?

**Comment by jigsshah** [comment]
Hey piotrdz,

Thanks for your reply i will try this and update the forum.

Warms regards,
Jigar

**Comment by jigsshah** [comment]
Hi piotrdz,

Thanks for your help, it working fine through your example. So closing the issue too.

Warms Regards,
Jigar
