### ISSUE TITLE
Show HTML template in tooltip

### ISSUE THREAD

**Issue by bharatModiIsMe** [angular-slider/ng5-slider#31]
In the option 'ticksTooltip', I want to return a dynamically created HTML template. Any way to achieve it?

**Comment by piotrdz** [comment]
You can supply your own template to render tooltips like in [this example](https://angular-slider.github.io/ng5-slider/#ticks-custom-tooltips-slider).

For example, you can create your own component that will go inside the tooltip and give the tooltip value as input. It's a bit more involved than generating the HTML in `ticksTooltip` callback, but you should be able to achieve the same effect.

**Comment by bharatModiIsMe** [comment]
thanks..will look at it

**Comment by pattarmanjunath50** [comment]
Hi,
ticksTooltip and ticksValuesTooltip not working for me.

**Comment by piotrdz** [comment]
@pattarmanjunath50 They seem to be working in the demo app ([ticksTooltip](https://angular-slider.github.io/ng5-slider/demos#ticks-tooltips-slider) and [ticksValuesTooltip](https://angular-slider.github.io/ng5-slider/demos#ticks-values-tooltips-slider)).
Can you provide an example of where they are not working for you?
