### ISSUE TITLE
Slider jump issue

### ISSUE THREAD

**Issue by dexbytesmanish** [angular-slider/ng5-slider#35]
_Originally posted by @dexbytesmanish in https://github.com/angular-slider/ng5-slider/issues/29#issuecomment-435308226_

**Comment by dexbytesmanish** [comment]
There is still one more issue remaing in this case. Slider is jumping to first closes value but that value is not being updated to model bindings hence model binded values are not showing updated values as the slider is actually having. Please check this ( [StackBlitz Example]) (https://stackblitz.com/edit/ng5-slider-issue-29-vh9erz) for the remaining issue.

**Comment by piotrdz** [comment]
Thanks for spotting this. Fixed in v1.1.5.

**Comment by dexbytesmanish** [comment]
Can you please provide Stackblitz example for the same ?

**Comment by piotrdz** [comment]
https://stackblitz.com/edit/ng5-slider-issue-29-fixed-again?file=src/app/app.component.ts
