### ISSUE TITLE
Clicking on tick (value) not always working

### ISSUE THREAD

**Issue by wvankuipers** [angular-slider/ng5-slider#36]
When trying to move the slider by only clicking a tick (or a tick value) the slider (most of the time) doesn't respond to the click events as expected. It is kind of hard to explain so I created a video of it:

https://youtu.be/L0krQc9KpLM

It also happens on the example page (for example [this one](https://angular-slider.github.io/ng5-slider/#intermediate-ticks-slider) and [this one](https://angular-slider.github.io/ng5-slider/#intermediate-ticks-slider/#custom-ticks-legend-slider))

I've tested on both a Mac in Chome (70), Firefox (63) and Windows in Edge (38)

_The problem doesn't occur on Windows in IE (11)!_

**Comment by wvankuipers** [comment]
Btw I'm using version `1.1.5`

**Comment by piotrdz** [comment]
Thanks for reporting this. It looks like I broke this for mouse events when working on touch events in issue #32. It's fixed now in master, and I'll release it in next version.

**Comment by Code-Crash** [comment]
Thanks, @piotrdz, I just started to use this lib and found this issue. please release it. :)

**Comment by piotrdz** [comment]
I delayed the release a bit to redesign the demo website a bit. All done now.

Closing as fixed with v1.1.6 release.
