### ISSUE TITLE
upgrade to angular6?

### ISSUE THREAD

**Issue by rs200x** [angular-slider/ng5-slider#39]
Hi,

as I'm using angular 6 I'm gettings warnings with the new version as it requires angular 5.
Is there a possibility for an upgrade?

regards
Robert

**Comment by mariusl-a** [comment]
Same problem here, though we're using angular 7. 

I rolled back to 1.1.5 meanwhile.

**Comment by piotrdz** [comment]
Ah, my bad. I changed the way peer dependencies are added to package.json, and I used `^5.0.2` instead of `>=5.0.2`. I fixed it in now in master.

Anyway, it's safe to ignore this warning. The slider works perfectly well in Angular 6 and 7.

**Comment by piotrdz** [comment]
Fix released with v1.1.7.
