### ISSUE TITLE
Slider does not correctly enforce ceil when ceil is a decimal

### ISSUE THREAD

**Issue by DanielRLevine** [angular-slider/ng5-slider#40]
**Expected behavior**
It should never be possible to slide slider past ceil value.

**Observed behavior**
When ceil is a decimal, it is possible to slide slider past ceil value.

**Steps to reproduce**
https://stackblitz.com/edit/ng5-slider-simple-slider-example-2dvpoo
Click on slider pointer and drag to the right.  With pointer at far right of slider, move mouse around while still holding mouse down.  Text showing slider value will move between 9.5 and 10 depending on where you put your mouse.

**Browsers creating issue**
Google Chrome 70.0.3538.77
Firefox 63.0.1
Safari 11.0.3

**ng5-slider versions**
I've only checked ng5-slider v. 1.1.1 and 1.1.6 and both create the issue.

**Comment by DanielRLevine** [comment]
I've only checked ng5-slider v. 1.1.1 and 1.1.6 and both create the issue.

**Comment by piotrdz** [comment]
The StackBlitz example you linked is for slider v1.1.3. I changed it to v1.1.6, but I can't seem to reproduce the issue: https://stackblitz.com/edit/ng5-slider-issue-40

**Comment by DanielRLevine** [comment]
Thank you for looking into this.  I revisited the issue and it appears that it was fixed in ^1.1.4.  Thanks for making such a great component!!!
