### ISSUE TITLE
Range slider with two input box can enter value which exceeds the slider range scope, then the slider range shows wrong

### ISSUE THREAD

**Issue by Sherry-Xu-2018** [angular-slider/ng5-slider#48]

**Comment by piotrdz** [comment]
Thanks for reporting this. I fixed the bug in master. I will make a new release soon.

**Comment by Sherry-Xu-2018** [comment]
Thank you very much for fixing this, could you please help me to merge this change to a new npm version, then I can use these new changes in my project.

**Comment by Sherry-Xu-2018** [comment]
> Thanks for reporting this. I fixed the bug in master. I will make a new release soon.

Waiting for new release!

**Comment by piotrdz** [comment]
I wanted to add some more content to the release, but that can wait.

I've released v1.1.9 with the fix.

**Comment by piotrdz** [comment]
I added the check for range invariant (low value always lower than high value). If the invariant is violated, the low and high values are switched around, unless `noSwitching` option is used, in which case the range is clipped to the same value.

I also noticed a subtle bug with using !== in normalisation code. The incoming model value can be a string if it comes from input box binding and the normalised value is a number. To avoid any problems, I decided to always convert input values to numbers.

**Comment by piotrdz** [comment]
Released v1.1.10 with the above changes.

**Comment by Sherry-Xu-2018** [comment]
> I added the check for range invariant (low value always lower than high value). If the invariant is violated, the low and high values are switched around, unless `noSwitching` option is used, in which case the range is clipped to the same value.
> 
> I also noticed a subtle bug with using !== in normalisation code. The incoming model value can be a string if it comes from input box binding and the normalised value is a number. To avoid any problems, I decided to always convert input values to numbers.

Wow...make it as a configurable `noSiwitching` option is a very good solution.

**Comment by Sherry-Xu-2018** [comment]
> Released v1.1.10 with the above changes.

Thanks very much!
