### ISSUE TITLE
Can we have html in the legend?

### ISSUE THREAD

**Issue by euroleaguedataguy** [angular-slider/ng5-slider#49]
Hi there,

great job! Was wondering if it's possible to have html in the legend as well?
In the example https://angular-slider.github.io/ng5-slider/demos#custom-legend-function-slider if I modify the getLegend function to return html it won't be rendered.

Thanks!

**Comment by piotrdz** [comment]
Yes, it's possible to add this functionality. I'll do it after holidays.

**Comment by piotrdz** [comment]
That's a very nice website, glad you can use the slider.

As promised, dynamic HTML in legend available in v1.1.12:
https://angular-slider.github.io/ng5-slider/demos#custom-legend-function-slider

**Comment by euroleaguedataguy** [comment]
Thanks @piotrdz  so much!!! Awesome!

**Comment by YiannisGkoufas** [comment]
Hi! Is it possible to post an example with the html legend using style? In my case if I set a <span> as legend it works, however <span style:"background-color:red"> doesn't seem to have an effect
