### ISSUE TITLE
Set range slider min&max value to null will get "toString" js error

### ISSUE THREAD

**Issue by Sherry-Xu-2018** [angular-slider/ng5-slider#50]
![screen shot 2018-12-18 at 4 02 39 pm](https://user-images.githubusercontent.com/28748127/50140378-7f681180-02df-11e9-949b-7058b7ffae3e.png)
![screen shot 2018-12-18 at 3 57 52 pm](https://user-images.githubusercontent.com/28748127/50140387-8b53d380-02df-11e9-9f99-c5a873d05813.png)

I tried with the latest version 1.1.9, clear the max value in the input box and try to type a new max value, then I got the js error.Seems like some edge cases forget to check in the library.

**Comment by piotrdz** [comment]
I can't reproduce the issue. In 1.1.9, it is not possible to clear the input box, because range checking will set the value to minimum.

Aside from that, I would say adding null checks is not the responsibility of the slider. The slider is supposed to be always bound to a valid model value and if that constraint is not satisfied, its behaviour is undefined. It will likely blow up, somewhere, sooner or later.

The problem with adding null checks is that it is not clear what behaviour is expected in case of a null. Should the value be changed to something else like minimum or maximum? Should it be ignored? Should the slider go into "undefined" state?
 
It is simply not clear what should happen, so I'm going to leave it as it is.

**Comment by Sherry-Xu-2018** [comment]
Highly appreciated for replying me, so quick feedback~~~I got it, always bind a valid model value to the slider.

BTW, from my side, for the minimum value, I can’t clear the input box, it always jump to the min value, but for the max value, I can clear the input box.





Thanks and best,
-Sherry


发件人: Piotr Dziwiński [mailto:notifications@github.com]
发送时间: 2018年12月18日 16:40
收件人: angular-slider/ng5-slider <ng5-slider@noreply.github.com>
抄送: Xu, Shan Shan <shanshan.xu@zeiss.com>; Author <author@noreply.github.com>
主题: Re: [angular-slider/ng5-slider] Set range slider min&max value to null will get "toString" js error (#50)


I can't reproduce the issue. In 1.1.9, it is not possible to clear the input box, because range checking will set the value to minimum.

Aside from that, I would say adding null checks is not the responsibility of the slider. The slider is supposed to be always bound to a valid model value and if that constraint is not satisfied, its behaviour is undefined. It will likely blow up, somewhere, sooner or later.

The problem with adding null checks is that it is not clear what behaviour is expected in case of a null. Should the value be changed to something else like minimum or maximum? Should it be ignored? Should the slider go into "undefined" state?

It is simply not clear what should happen, so I'm going to leave it as it is.

**Comment by piotrdz** [comment]
I looked again at the normalising code and there was a subtle bug in there with using !== and === on input value which is string and normalised value which is number.

What I decided to do is to always convert input values to numbers. This means that null or empty string will be treated as 0, and undefined as NaN, which is in a way reasonable, but again it's a grey area, and this behaviour shouldn't be relied on.

With additional range check that I'm adding as continuation of #48, I'm pretty sure this problem will not be occurring anymore.

**Comment by Sherry-Xu-2018** [comment]
Cool~~

发件人: Piotr Dziwiński [mailto:notifications@github.com]
发送时间: 2018年12月18日 17:26
收件人: angular-slider/ng5-slider <ng5-slider@noreply.github.com>
抄送: Xu, Shan Shan <shanshan.xu@zeiss.com>; Author <author@noreply.github.com>
主题: Re: [angular-slider/ng5-slider] Set range slider min&max value to null will get "toString" js error (#50)


I looked again at the normalising code and there was a subtle bug in there with using !== and === on input value which is string and normalised value which is number.

What I decided to do is to always convert input values to numbers. This means that null or empty string will be treated as 0, and undefined as NaN, which is in a way reasonable, but again it's a grey area, and this behaviour shouldn't be relied on.

With additional range check that I'm adding as continuation of #48<https://github.com/angular-slider/ng5-slider/issues/48>, I'm pretty sure this problem will not be occurring anymore.

**Comment by Sherry-Xu-2018** [comment]
> I looked again at the normalising code and there was a subtle bug in there with using !== and === on input value which is string and normalised value which is number.
> 
> What I decided to do is to always convert input values to numbers. This means that null or empty string will be treated as 0, and undefined as NaN, which is in a way reasonable, but again it's a grey area, and this behaviour shouldn't be relied on.
> 
> With additional range check that I'm adding as continuation of #48, I'm pretty sure this problem will not be occurring anymore.

I totally agree with you about Point2, not relay on this to do the error handling, but I still have some thoughts about this Point2.
Just now I tried the new version 1.1.10 demo of the range slider, as now using number to compare, about how to handle `NAN` I think still some improvement can be done.

Now the demo behavior is if I input invalid value, e.g. i input a negative number, the range slider will show the `NAN`, should we also change `NAN` to a reasonable value, maybe for input min value change to range.floor, max value changes to range.ceil.

**Comment by Sherry-Xu-2018** [comment]
Ok.I limit the two input boxes input values, always keep them can input the valid values, then I still can use the [(ngModel)] to bind the minValue  and maxValue to these two input boxes.
