### ISSUE TITLE
ng5-slider with range input has weird behavior when placed in a dropdown.

### ISSUE THREAD

**Issue by stijnwesterhof** [angular-slider/ng5-slider#51]
![image](https://user-images.githubusercontent.com/15048777/50215969-d4119800-0384-11e9-8486-fbf6f82dcbcf.png)

As you can see in the image above the range slider is not displaying correctly. It's placed in a bootstrap dropdown nav. When I copy and paste it somewhere else it looks fine. Any idea how to fix this? 

![image](https://user-images.githubusercontent.com/15048777/50215989-decc2d00-0384-11e9-9743-6dc894ba58f4.png)
This is how it should look like.

**Comment by Sherry-Xu-2018** [comment]
I also encountered this problem when I firstly used this slider.

One solution you can refer "Slider with manual refresh" demo to resolve this issue. Use slider's  'manualRefresh' option to trigger a refresh manually when you toggle on the dropdown list.

Another solution now I use in my project is using *ngIf="display" in 'ng5-slider' tag, change the display variable according to toggling on/off dropdown list.

**Comment by stijnwesterhof** [comment]
Tried your fix and it works! Thanks 👍
