### ISSUE TITLE
Commit 0eb5914 breaks the case with stepsArray option defined

### ISSUE THREAD

**Issue by benoitbzl** [angular-slider/ng5-slider#52]
The new function normaliseLowValue() does not take into account the Options.stepsArray field. So changing the slider value (without interacting with the graphical element) moves the slider always at the beginning of bar.

**Comment by piotrdz** [comment]
Can you please provide a reproduction example? When using `stepsArray` option, `floor` and `ceil` are set based on array bounds, so the normalisation check should still work. If you are seeing the slider move to the first value, then perhaps the value in the input element is invalid or falls outside the bounds and parsed as zero?

**Comment by benoitbzl** [comment]
I forget to point that I am using dates for the slider value (as explain in the examples). See example https://stackblitz.com/edit/ng5-slider-52

**Comment by piotrdz** [comment]
I see, this is where you also use custom translate function. I've disabled the normalisation code when `stepsArray` is specified. I will release a new version in a moment.

**Comment by piotrdz** [comment]
Fix released in v1.1.11.

**Comment by benoitbzl** [comment]
That was fast! Thanks!

**Comment by piotrdz** [comment]
No worries. Last thing to tick off before Christmas holidays.
