### ISSUE TITLE
Change direction to RTL

### ISSUE THREAD

**Issue by IgorRomanvsky** [angular-slider/ng5-slider#57]
How can i change the direction of the slider from right to left?
Thanks

**Comment by ahmadmu** [comment]
Did you try setting the `rightToLeft` key in the options object to `true`? 
https://angular-slider.github.io/ng5-slider/demos

**Comment by piotrdz** [comment]
`rightToLeft = true` is the correct way to change the direction to right to left, so closing issue. If there are any concerns, please provide an update and I can re-open the ticket if necessary.

**Comment by egalot** [comment]
Does it change when the value is set dynamically after the slider is initiated? I have not been able to set the rightToLeft property dynamically. Even after invoking manualrefresh.
