### ISSUE TITLE
Dynamic min and max value for handles are not being applied

### ISSUE THREAD

**Issue by bdparrish** [angular-slider/ng5-slider#58]
I am attempting to dynamically change my slider from chronological dates to chronological time.  I am able to get the labels and increments correct, but the handles are not changing to their appropriate min and max values that are being set with two binding.

The handles are maintaining their long epoch values from the date even though I have change them in the code below.

```html
<ng5-slider [(value)]="minValue" [(highValue)]="maxValue" [options]="options" (userChange)="onChange($event)"></ng5-slider>
```

The handles are maintaining their long epoch values from the date even though I have change them in the code below.

```javascript
this.minValue = 0;
this.maxValue = 1440;

this.options = {
    floor: 0,
    ceil: 1440,
    stepsArray: this.createTimeRange().map((number: number) => {
        return { value: number };
    }),
    translate: (value: number, label: LabelType): string => {
        const hours: number = Math.floor(value/60);
        const hoursString = (hours < 10) ? "0" + hours : "" + hours;
        const minutes: number = value % 60;
        const minutesString = (minutes < 10) ? "0" + minutes : "" + minutes;
        return hoursString + ":" + minutesString;
    },
    showSelectionBar: true,
    noSwitching: true
};
```

I have looked at your stackblitz examples and I cannot get it to recreate there.  The only thing I didn't recreate were the options variable.

**Comment by bdparrish** [comment]
It looks like it is using my index count from steps array to set min and max value, but the handles are still not show correctly.

**Comment by markusila** [comment]
setNewCeil(newCeil: number): void {
    // Due to change detection rules in Angular, we need to re-create the options object to apply the change
    const newOptions: Options = Object.assign({}, this.options);
    newOptions.ceil = newCeil;
    this.options = newOptions;
  }

**Comment by bdparrish** [comment]
I can definitely see where it call `onChangeValue` then `onChangeHighValue` before it calls `onChangeOptions` for the options.  This is the order it calls if I set my `minValue` and `maxValue` before or after I set my `options` value.  Is there a work around for this at all?

**Comment by piotrdz** [comment]
A workaround using `setTimeout()` is possible, but shouldn't be necessary now. I just released v1.1.12 of slider which should fix this. Can you re-test your code with the new version?

**Comment by bdparrish** [comment]
@piotrdz takes a step in the right direction.  the initial state of the slider is now correct, but when i go to dynamically change the slider it falls back to the previous behavior where the handles are being changed before the options.

**Comment by bdparrish** [comment]
@piotrdz Awesome, looks good and fixes my issue.
