### ISSUE TITLE
Data is not updated from the component when using reactive forms

### ISSUE THREAD

**Issue by jokernix** [angular-slider/ng5-slider#61]
I used range slider in reactive form. But when I needed to reset the form, the values in the slider did not change. I made an example on [StackBlitz](https://stackblitz.com/edit/angular-iysmc2?file=src%2Fapp%2Fapp.component.html)
Thanks

**Comment by piotrdz** [comment]
Fix released in v1.1.3 ([StackBlitz](https://stackblitz.com/edit/ng5-slider-issue-61-62-fixed)).
