### ISSUE TITLE
View is not updated when updating formControl value

### ISSUE THREAD

**Issue by artonio** [angular-slider/ng5-slider#62]
```
@Component({
  selector: 'app-root',
  template: `
    <ng5-slider [options]="options" [formControl]="sliderControl"></ng5-slider>
  `,
  styleUrls: ['./app.component.css']
})
export class AppComponent implements AfterViewInit {

  value = 5;
  options: Options = {
    floor: 0,
    ceil: 10,
    showTicks: true,
    getLegend: (value: number): string => {
      return '<b>T</b>' + value;
    }

  };

  sliderControl: FormControl = new FormControl(5);

  ngAfterViewInit(): void {
    this.sliderControl.setValue(2);
  }
}
```

Initial value is 5 and the view is set correctly. Now we will set the value to be 2. After some investigation it seems that the SliderComponent variable 'value' is set to 2 but the view is never updated.

also a dupicate of: https://github.com/angular-slider/ng5-slider/issues/61

**Comment by piotrdz** [comment]
Thanks for reporting this. I have merged the fix, but I want to write some more tests before releasing new version.

**Comment by piotrdz** [comment]
Fix released in v1.1.3 ([StackBlitz](https://stackblitz.com/edit/ng5-slider-issue-61-62-fixed)).

**Comment by MickL** [comment]
Oh i was confused for a minute, you mean `1.1.13` right? Thanks so much i just had the same issue, update fixed it!

**Comment by piotrdz** [comment]
Yes, that was 1.1.13
