### ISSUE TITLE
Slider does not display the range

### ISSUE THREAD

**Issue by tzofiaCo** [angular-slider/ng5-slider#65]
This is my code:
`export class SearchAreaComponent implements OnInit {

  minPrice: number;
  maxPrice: number;
  options: Options;

  constructor(private _searchAreaDataService: SearchAreaDataService) {
  }
 

  ngOnInit() {
    this.initialSlider()
  }

  initialSlider() {
    this._searchAreaDataService.getMaxPrice().subscribe(result => {
      this.maxPrice = result as number;
      this.minPrice = 0;
      this.options = {
        floor: this.minPrice,
        ceil: this.maxPrice,
        step: 100,
        translate: (value: number): string => {
          return '₪' + value;
        }
      };
    }, error => console.error(error));
  }`

And that's what happens:
![image](https://user-images.githubusercontent.com/23309640/51890939-3c9d5d00-23a6-11e9-8183-ba02acaa0d1b.png)

I want it to look like this:

![image](https://user-images.githubusercontent.com/23309640/51890996-68204780-23a6-11e9-8fce-e4c0cb31afb7.png)

Thanks!!

**Comment by piotrdz** [comment]
Well, it looks like the slider is getting the correct data, but it's not updating the view correctly. I tried to reproduce it [on Stackblitz](https://stackblitz.com/edit/ng5-slider-issue-65?file=src/app/app.component.ts), but it's working correctly for me.

I suspect that in your case, you are showing the component dynamically, like in a popup? If so, you will need to trigger [manual refresh](https://angular-slider.github.io/ng5-slider/demos#manual-refresh-slider) to update the view.

**Comment by tzofiaCo** [comment]
Yes! it is in collapse div, using manual refresh fix it. thank!!

**Comment by piotrdz** [comment]
Glad to hear.
