### ISSUE TITLE
Slider ticks stacked when first loaded

### ISSUE THREAD

**Issue by quintusvw** [angular-slider/ng5-slider#67]
I've implemented the slider in a modal in Angular, but the slider ticks are stacked one upon the other when the modal is first loaded. Once I click anywhere near or on it, it displays the distributed ticks as it should.

![screen shot 2019-02-04 at 14 56 36](https://user-images.githubusercontent.com/17273845/52209757-8a760180-288d-11e9-9657-6a1924e9cb16.png)

I use a directive to load the modal content dynamically.

    value: number = 5;
    options: Options = {
        floor: 0,
        ceil: 5,
        showTicksValues: true,
        ticksValuesTooltip: (v: number): string => {
            return 'Tooltip for ' + v;
        },
        stepsArray: [
            {value: 1, legend: 'None'},
            {value: 2, legend: 'Low'},
            {value: 3, legend: 'Average'},
            {value: 4, legend: 'Important'},
            {value: 5, legend: 'High'}
        ]
    };

<ng5-slider [(value)]="value" [options]="options" style="width: 100%;"></ng5-slider>

Thanks.

**Comment by piotrdz** [comment]
If you display content dynamically, you should use [manualRefresh](https://angular-slider.github.io/ng5-slider/docs#manual-refresh) to update the slider.

**Comment by thilinaalwis** [comment]
using [manualRefresh ](https://angular-slider.github.io/ng5-slider/docs#manual-refresh) solved the issue for me.

**Comment by piotrdz** [comment]
I documented this problem more clearly as a known issue. Closing ticket.
