### ISSUE TITLE
If the value is not number ChangeContext returns value as NaN

### ISSUE THREAD

**Issue by thilinaalwis** [angular-slider/ng5-slider#68]
I am binding time (ex: "08:00") as value. It works perfectly in the view. But when I am trying to get the selected values using onUserChangeEnd() . value return as null

Returns This

`ChangeContext {pointerType: 1, value: NaN, highValue: NaN}` @piotrdz

**Comment by thilinaalwis** [comment]
It's my bad there are enough examples to this great component. I was able to figure it out while going through the [examples](https://angular-slider.github.io/ng5-slider/demos).

**Comment by piotrdz** [comment]
Only numeric values are supported as inputs, but I'm glad you found a solution that works for you.
