### ISSUE TITLE
ng5-slider Value change events not working

### ISSUE THREAD

**Issue by cshen19** [angular-slider/ng5-slider#69]
I use <ng5-slider> in the angular form. The value of input textbox is binding to ng5-slider's value.
But valueChanges event is NOT fired, whenever the model values is changed in the input box without clicking slider.

The valueChanges event is fired only when I use two way data binding in the ng5-slider [(value)]="value"
and click slider. I would like to have  valueChanges event  fired when binding value in the slider changed.

public value: number = 100;
  public options: Options = {
    floor: 0,
    ceil: 200
  };

- html 
<p>Value: <input type="number" [(ngModel)]="value"></p>
 <ng5-slider [value]="value"  [options]="options" (valueChange)="sliderChange($event)"></ng5-slider>

**Comment by piotrdz** [comment]
If I understand correctly, you would like to see events coming through even if the change did not originate in the slider [like in this StackBlitz](https://stackblitz.com/edit/ng5-slider-issue-69?file=src%2Fapp%2Fapp.component.html). I agree, that should be fixed and I'll do that.

**Comment by piotrdz** [comment]
I tried adding this feature, but for some reason, I broke e2e tests in CI build. I will need to investigate it a bit more, so I will skip it in this release.

**Comment by piotrdz** [comment]
This is fixed by recent changes re-writing a lot of value update code. It will be available in next release, coming in next day or two.

**Comment by piotrdz** [comment]
Fix released with v1.2.0.
