### ISSUE TITLE
Not able to apply ngClass in legend attribute of stepsArray

### ISSUE THREAD

**Issue by sorabh2008** [angular-slider/ng5-slider#70]
trying to apply ngClass in legend attribute in stepsArray like:
```
stepsArray = [
{
value: 10,
legend: `<span [ngClass]="{'legend': true}">Hello</span>`
}
]
```

Also, if I add a normal HTML class attribute, it works like a charm
```
stepsArray = [
{
value: 10,
legend: `<span class="legend">Hello</span>`
}
]
```

Is there any way to achieve this?
PS: I tried to use getLegend() but somehow it never gets called when using stepsArray.

**Comment by piotrdz** [comment]
Unfortunately, this isn't so simple.

What you are providing here in legend is basically a static text, or HTML, that is pasted into DOM.

To have it behave as a dynamic template with Angular bindings, you would have to instantiate an Angular component in place of the static text.

It is possible to do in principle, using transclusion or even [on-the-fly component compilation](https://blog.angularindepth.com/here-is-what-you-need-to-know-about-dynamic-components-in-angular-ac1e96167f9e).

However, this would be a huge amount of work with little benefit in the library, so I have no plans to support it. Sorry.
