### ISSUE TITLE
Add animations

### ISSUE THREAD

**Issue by ValentinH** [angular-slider/ng5-slider#72]
Hey @piotrdz,

In the 7.0.0 version of `angularjs-slider` I have added animation for the sliders. I think it is a cool feature and could be easily added on the ng5 version too 🙂 

Here's my commit: https://github.com/angular-slider/angularjs-slider/commit/099b5f8e7dab337235e91a54b9a4fb7908f0ba74

**Comment by piotrdz** [comment]
Thanks @ValentinH. I will add the feature to ng5-slider.

**Comment by piotrdz** [comment]
I had some trouble with applying the animation transitions to slider ticks, so I will skip this release, but I will work to get this out in next one.

**Comment by piotrdz** [comment]
I managed to fix the outstanding problems - animations are now in master and I will release that in a new version soon.

I also decided to change the CSS around - the slider has an `animate` class that turns the animations on and if it doesn't have this class, animations are turned off. I think it's a bit clearer that way than using `noanimate` class, and it avoids using `!important`.

**Comment by alisalama** [comment]
Hi @piotrdz, excellent work! Any idea when these animations will be released? Would be awesome!

**Comment by piotrdz** [comment]
Animations are now released in v1.2.0.
