### ISSUE TITLE
highValue also changes when changing value

### ISSUE THREAD

**Issue by A1996KASH** [angular-slider/ng5-slider#75]
When I am sliding from the left side  it should only change the value but it also changes the highValue this issue I am using milliseconds  as the values.

**Comment by piotrdz** [comment]
I don't quite understand - is the high value changing when you slide the low value handle? Can you post an example StackBlitz with your code? You can fork and edit for example [this one](https://stackblitz.com/edit/ng5-slider-range-slider-example?file=src%2Fapp%2Fapp.component.ts).

**Comment by MRebati** [comment]
I had the same issue on rtl pages. the workaround is to use the manualRefresh on ngAfterViewInit()
