### ISSUE TITLE
Dynamic component 

### ISSUE THREAD

**Issue by Dovernh** [angular-slider/ng5-slider#8]
I’m using dynamic components with min and max. When unhidden the sliders are both on zero. I have ngModel showing the values and I’m seeing the correct values of zero and 100. Is there a way to force the slider to update itself?

**Comment by Dovernh** [comment]
I discovered that if I use an *ngIf and only show the slider when I wish to see it, it will correctly display.

**Comment by piotrdz** [comment]
Thanks for reporting this problem. There is no way of refreshing the slider manually, except for changing the inputs.

 I'm not exactly sure what's causing this behaviour you are describing. If possible, could you provide an example plunker? You can create your own based on the example from https://plnkr.co/XhzcMg

**Comment by Dovernh** [comment]
I'm closing this issue as I have a work around.
