### ISSUE TITLE
Violation error in console

### ISSUE THREAD

**Issue by vaishravi5** [angular-slider/ng5-slider#85]
ng5-slider- **v1.1.3**

Integrated the ng5-slider.  slider is integrated like below:

 <ng5-slider [options]="sliderOption"
                  (userChangeEnd)="onSlideChangeEnd()"></ng5-slider> 

Here is my sample sliderOption 

sliderOption =  { 
      floor: 10,
      ceil: 30,
      getPointerColor: (value: number) => pointerValue,
      showSelectionBar: true,
      rightToLeft: true/false,
      ticksArray: tickArray,
      disabled: true/false
}

getting Violation error in console, due to that facing **performance impact**

Refer the attached screen shot

![new](https://user-images.githubusercontent.com/48748677/54666602-28f1b580-4b10-11e9-8492-a88966880062.png)

Note:

Upgraded ng5-slider version to  **v1.1.6** 

Violation error resolved but still facing performance issue

**Comment by piotrdz** [comment]
Can you elaborate on the performance issue you are facing? Do you also have problems with the current version (1.1.14)?

**Comment by vaishravi5** [comment]
Load handler tooks n+ ms (Based on number of slider).

**Comment by piotrdz** [comment]
Performance on initial page load is a known issue tracked under #45.
I don't see anything else that would be actionable here, so I'll close this as duplicate.
