### ISSUE TITLE
Custom slider doesn't seem to work with Angular 7

### ISSUE THREAD

**Issue by chrisid** [angular-slider/ng5-slider#87]
**::ng-deep**
does not work anymore, any idea on how to style the slider bar?

I'm adding: **encapsulation: ViewEncapsulation.None**, but I'm not sure that's good practice.

```
@Component({
	selector: 'app-rating',
	templateUrl: './rating.component.html',
	styleUrls: ['./rating.component.scss'],
	encapsulation: ViewEncapsulation.None
})
```

**Comment by piotrdz** [comment]
Well, `::ng-deep` was going to be removed at some point, so I guess it's not a surprise.

The thing is, `::ng-deep` by itself doesn't do anything special - it's a bit like putting the same CSS into your global `styles.css`/`styles.scss` and applying it globally across the app.

Disabling view encapsulation is sort of the same thing - the style you add to your component CSS will end up as part of the global CSS in the compiled app. But at the same time you lose the benefits of Shadow DOM being used for wrapping and isolating your component.

My advice would be to add the style to global `styles.css`/`styles.scss` and using specific CSS classes to identify which slider components you want to be styled or not.

I will add this to the documentation in next release.

**Comment by piotrdz** [comment]
Actually, wait, I can get `::ng-deep` to work in Angular 7, see [this Stackblitz](https://stackblitz.com/edit/ng5-slider-issue-87?file=src%2Fapp%2Fapp.component.scss).

Are you using a CSS selector with enough specificity? Does `!important` change anything?

**Comment by piotrdz** [comment]
I'm going to assume that this works in Angular 7. If you are still experiencing problems, please reopen.
