### ISSUE TITLE
When i put MaxValue the slider only show after i click on it!

### ISSUE THREAD

**Issue by astrO1** [angular-slider/ng5-slider#88]
Why this is happening?

The slider is working fine, but when I put the slider to start on maxValue he only shows this when I click on the slider, not when I enter on the page.

why this?

**Comment by piotrdz** [comment]
Do you mean starting the slider on `ceil` value or `maxLimit` value? Can you provide an example of code you are using? A StackBlitz would be quite helpful (for example forking [this one](https://stackblitz.com/edit/ng5-slider-range-slider-example?file=src%2Fapp%2Fapp.component.ts)).

**Comment by willhs** [comment]
I'm also experiencing this. In my case it's when the slider is hidden at first. In other words when it doesn't render immediately (at least that's what seems to be happening) but the controller does initiliase immediately.

When the slider becomes visible the max value slider handle is displayed at 0 even though it is set to a higher value (aria-valuenow and other attributes on the handle are set to the correct value). Then once I interact with the slider or resize the page the handle sets to the correct position.

**Comment by saramalla** [comment]
I see the same behavior. Slider pointers don't set properly if the component is not visible when initialized. I got around this by not initializing the component until the parent component is visible (using a simple *ngIf).

**Comment by piotrdz** [comment]
I see. This is a known issue with a workaround being the use of `manualRefresh`. See [KNOWN_ISSUES.md](https://github.com/angular-slider/ng5-slider/blob/master/KNOWN_ISSUES.md) which is linked in README. Triggering `manualRefresh` at appropriate time should re-draw the slider.
