### ISSUE TITLE
[QUESTION] How to disable the slider

### ISSUE THREAD

**Issue by vishnu-dev** [angular-slider/ng5-slider#90]
Is there any way to disable the slider? I want to disable the slider for some time based on a flag.

**Comment by piotrdz** [comment]
You can use `disabled` flag in slider options as in [this demo](https://angular-slider.github.io/ng5-slider/demos#disabled-slider).

**Comment by vishnu-dev** [comment]
@piotrdz Totally missed out that example. Thanks for the help.

**Comment by hexiaoli999** [comment]
怎么禁用其中一个slider

**Comment by hexiaoli999** [comment]
How do I disable one of the sliders
