### ISSUE TITLE
strange behavior when setting value and highValue in code

### ISSUE THREAD

**Issue by strapsi** [angular-slider/ng5-slider#91]
Hello,
i really like the ng5-slider but i came across a strange bug recently. i use the slider with value and highValue. when i set both of those values to the same number on button click it sometimes works as expected but sometimes it doesn't react at all or messes up the slider completely.

i use ng5-slider v1.1.14. 
i also tried it with v.1.1.13 and everything works perfectly. 

[Stackblitz](https://stackblitz.com/edit/ng5-slider-simple-slider-example-g9eigq) to reproduce the bug

thanks a lot, bye.

**Comment by piotrdz** [comment]
In recent changes, I re-wrote most of value update and normalisation code using rxjs, fixing a lot of similar bugs.

This should be fixed once I make the next release in the next day or two.

**Comment by piotrdz** [comment]
Fix released with v1.2.0.
