### ISSUE TITLE
Entering the value out of the range (0 - 100) 

### ISSUE THREAD

**Issue by AnaRankovic** [angular-slider/ng5-slider#95]
Hello, I would appreciate if someone could help me with this...
When I provide the value (via keyboard) that is out of the range (0 - 100), and then I try entering allowed value(0 - 100), slider doesn't reflect this change, and stays freezed.
Thank you in advance.

![Capture](https://user-images.githubusercontent.com/10993647/57128354-6a25e800-6d93-11e9-8e09-05ccadef6c05.PNG)

**Comment by piotrdz** [comment]
In recent changes, I re-wrote most of value update and normalisation code using rxjs, fixing a lot of similar bugs.

This should be fixed once I make the next release in the next day or two.

**Comment by piotrdz** [comment]
Fix released with v1.2.0.
