### ISSUE TITLE
set touched or active programmatically

### ISSUE THREAD

**Issue by AndreKelling** [angular-slider/ng5-slider#97]
is there a way to set a slider to touched or active state?

for UI / styling reasons in my view the pointers have different colors for default state and another color for hover, focus, active and touched state.
then there is a form which can be already filled out prior, and so the slider where touched once already when the user comes back.

i did not found an option to do so.

it's similar to this https://github.com/angular-slider/ng5-slider/issues/93 or this https://github.com/angular-slider/ng5-slider/issues/64

**Comment by piotrdz** [comment]
I don't quite understand the use-case here. Does setting focus programmatically like in #64 not work for you?

**Comment by AndreKelling** [comment]
setting focus is that my current cursor will be on the slider handle.

what i try to achieve is once i touched a slider, the handle shall get shown active all the time.

in my case it's possible to come back to the component later. the sliders will be untouched again. but i know that the user once have changed them. so i would like to set them active programmatically.
currently i do this:
```
const sliderEl = this.el.nativeElement.querySelectorAll('.ng5-slider');
sliderEl.forEach(
          function(currentValue) {
            currentValue.classList.add(this);
          },
          'ng-touched'
      );
```
maybe there is already a better way to do so?!

**Comment by piotrdz** [comment]
Well, `ng-touched` is a class that Angular applies to form controls that use `ngModel`. The slider doesn't use `ngModel` and there is no separate styling that is applied on touching the control.

But if you do want to style the slider differently, using `ng-touched` class, or any other class for that matter, you can add them to the slider tag:

```
<ng5-slider class="ng-touched" [(value)]="value" [options]="options"></ng5-slider>
```

This can also be conditional:
```
<ng5-slider [class.ng-touched]="condition" [(value)]="value" [options]="options"></ng5-slider>
```
And then set the `condition` in your component when appropriate.

I hope that helps.

**Comment by AndreKelling** [comment]
that's it.

kind of obvious..

thanks!
