### ISSUE TITLE
Disable Range Click in Slider

### ISSUE THREAD

**Issue by tcoz** [angular-slider/ng5-slider#98]
I've seen a few people mention that when you click the "selected range" portion of the slider when draggableRange is enabled, the closest handle will jump to the selection point, then jump back when you start dragging; the feedback from users is it's undesirable (confusing and whatnot). I have an outstanding PR to fix the issue (add "disableRangeClick" to options). We're using the widget in a production app to be released very soon, would be great to get an updated version with this added (for the time being we've decided we can "live with it", but it's definitely a detractor from the overall UX). Let me know if there's anything I can do to help get it merged.

Thanks, great widget btw. Would love to see the animations enabled as well.

**Comment by piotrdz** [comment]
Thanks. I decided to provide my own fix for the original issue that was reported for this (#80)

**Comment by tcoz** [comment]
Is this available now?

**Comment by piotrdz** [comment]
Yes, it is available now. I just released v1.2.0.

**Comment by tcoz** [comment]
Excellent, thank you.

**Comment by tcoz** [comment]
I think there may be a problem with this update. As soon as I updated to it (did a completely fresh build etc), as soon as you move one of the sliders (onMove), an error is thrown; the slider moves chaotically/erratically, ultimately pinning to the max. 

Downgrading back to 1.1.14 cleaned it right up. 

push../node_modules/ng5-slider/esm5/ng5-slider.js.SliderComponent.onMove
....
attr.js:31 Error: <circle> attribute r: Expected length, "NaN".

Let me know if you need more info.

**Comment by piotrdz** [comment]
@tcoz: Please raise a new issue with the slider options you are using or preferably, a StackBlitz reproduction (you can fork one of the existing ones for [simple slider](https://stackblitz.com/edit/ng5-slider-simple-slider-example?file=src%2Fapp%2Fapp.component.ts) or [range slider](https://stackblitz.com/edit/ng5-slider-range-slider-example?file=src%2Fapp%2Fapp.component.ts)).
